### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by daniel-lerch** [Twometer/NeonRacer#12]
Passend zum Neon-Stil und den verschiedenen Autos müssen Sounds entworfen/gefunden werden und mit einer Sound-Engine abgespielt werden. Dabei sollte die Motorlast zumindest grob berücksichtigt werden.

**Comment by Twometer** [comment]
Das hat jedoch keine hohe Priorität und die Anwendung kann auch ohne dieses Feature ausgeliefert werden

**Comment by daniel-lerch** [comment]
Für dieses aufwändige Feature reicht die Zeit nicht mehr. Das Spiel muss ohne Sounds fertiggestellt werden.
