### ISSUE TITLE
Projektplanung

### ISSUE THREAD

**Issue by daniel-lerch** [Twometer/NeonRacer#14]
Die Auftraggeberin verlangt eine Dokumentation der Projektplanung. Dazu müssen folgende Punkte abgedeckt sein:
- [x] Magisches Dreieck
- [x] Projektumfeldanalyse
- [x] SMARTe Ziele (siehe GitHub Issues)
- [x] Projektstrukturplan
- [x] Aufwandsabschätzung
- [x] Risikomanagement
- [x] Terminplanung

Außerdem ist eine Dokumentation des erstellten Programms nötig:
- [ ] Klassenstruktur
- [x] Entwicklungsumgebung/Setup
- [x] Herausforderungen
- [ ] Quellenverzeichnis

**Comment by Twometer** [comment]
Format bitte Markdown
