### ISSUE TITLE
Entities auf der Rennstrecke

### ISSUE THREAD

**Issue by daniel-lerch** [Twometer/NeonRacer#26]
Das bisherige Modell zur Definition von Entities funktioniert eigentlich nur für Items, mit denen der Spieler Fähigkeiten bekommt. Statische Entities wie z.B. Häuser, Container, Fabriken, usw. lassen sich damit aber nur sehr schlecht definieren.

- [x] Entity Definition neu konzipieren
- [x] Entity Rendering implementieren
- [x] Track-Designer erweitern

**Comment by Twometer** [comment]
Das schöne ist, die bisherige Definition funktioniert nur, wenn du nur einen einzigen Typ von Items hast. Es gibt nämlich keine Möglichkeit, den Entities Parameter zuzuweisen.
