### ISSUE TITLE
Präsentation vorbereiten

### ISSUE THREAD

**Issue by daniel-lerch** [Twometer/NeonRacer#33]
Das Projekt _Neon Racer_ soll dem Informatikkurs präsentiert werden. Insgesamt stehen dafür ca. 45 Minuten zur Verfügung, wobei aber auch Zeit für Rückfrage einkalkuliert sein sollte.

### Gliederung ###
- Einleitung: _@jrheiner_
  - Ideenfindung
  - Warum Rennspiel?
  - Welche anderen Ideen?
- Kommunikationsstruktur: _@daniel-lerch_
  - Git/Wiki, Wire, ownCloud
- Gameplay: _@Johlitos_
  - Spielablauf
  - Autos/Items
  - Ursprüngliche Überlegungen
- Graphische Gestaltung: _@jrheiner_
  - Neon Konzept
  - Entwurfspipeline
  - Designtagebuch
- Technischer Aufbau: _@Twometer_
  - Datenmodell
  - IntelliJ Projekt
  - OpenGL
  - Client Struktur
- Multiplayer Protokoll: _@daniel-lerch_
  - Protobuf
  - Messages
  - Server
- Physik-Engine: _@QXTR_
  - Aktuelle Implementation
- Theoretische Planung: _@QXTR_
  - Magisches Dreieck
  - Projektumfeldanalyse
  - Projektstrukturplan
- Projekt Management: _@daniel-lerch_
  - Aufgabenverteilung
  - Issues/Milestones
  - Herausforderungen
- Live Demo: _@Johlitos_

**Comment by Twometer** [comment]
Was da aber unter absolut keinen Umständen fehlen darf, ist eine Live Demo!
