### ISSUE TITLE
Physics debug visuals erstellen

### ISSUE THREAD

**Issue by snow-lumi** [Twometer/NeonRacer#44]
Ich brauche zum Debugging und zur besseren Implementation der physics engine real time graphische Darstellungen der Hitboxen und von beliebigen 2D-Vektoren.

**Comment by Twometer** [comment]
Kommt drauf an, was du für Hitboxen hast. Da die nicht Axis Aligned sind, musst du wahrscheinlich die Eckpunkte als Linien in ein `Mesh` (siehe Mesh.java) packen, dann das Mesh mit `Model.create(mesh, GL_LINES)` in ein Line Model umwandeln, und das Model dann jedes Frame drawen (`model.draw`). Das machste für jede Hitbox, und dann haste deinen Renderer. Musst aber drauf achten, welchen Shader du da nimmst.

Für die 2D Vektoren kannste wieder das Line model erstellen und dann dem sagen von wo nach wo er ne line machen soll, die line ist dann dein Vektor.

**Comment by snow-lumi** [comment]
Das problem ist, dass ich mich weder mit opengl noch mit deinem code gut genug auskenne um irgendetwas davon zu machen.

**Comment by Twometer** [comment]
Ich hab im Moment aber keine Zeit mich darum zu kümmern. Ich hab dir da oben erklärt wie du das angehen kannst, der Code ist nicht so schwer zu verstehen, wenn man sich bisschen damit beschäftigt. Wenn du Fragen hast, helf ich dir auch, aber ich hab keine Zeit da jetzt riesigen Code zu schreiben.

Du kannst dir ja mal anschauen, wie die Entities gerendert werden. Da siehst du wie `Mesh` und `Model` verwendet werden, das kannst du relativ einfach auf dein Anwendungsgebiet übertragen.

**Comment by daniel-lerch** [comment]
Die Arbeiten an der neuen Physik-Engine sind vorerst abgeschlossen. Das Fahrverhalten ist gut genug, um Spaß mit dem Spiel haben zu können. Damit sind weitere Debug-Funktionen vorerst nicht mehr nötig.
